### ISSUE TITLE
Exception Handling in ProcessingChain

### ISSUE THREAD

**Issue by mmatteo** [legend-exp/pygama#130]
Can the ProcessingChain handle exceptions raised by the processors? 

If a processor fails for a waveform, all processors depending on it should be skipped. I would also store a failedFlag in the dsp tier to summarize the exit status of all processors.

What do you think?

**Comment by iguinn** [comment]
Hey Matteo,
Thanks for raising this issue! This is still something that needs work. Right now, an exception should stop the full run, which will almost never be the desired behavior (perhaps if there is a case where a processor would just always fail this would make sense?). I believe that numba will properly throw the python exceptions if they occur in processors, so the solution is just going to be to add a try-catch block in the right place in the code. One important thing to keep in mind is that since waveforms are processed in blocks, it is not possible to skip just a single waveform; it would instead skip all waveforms in a block!

For the failedFlag, would this just be one bool for each processor so that at the end we can print out a list of failures?

**Comment by mmatteo** [comment]
@iguinn, thanks for the explanation. PR #129 contains an example of a processor that will fail for low energy events. The processor is supposed to compute the log of the samples and, before running, it checks that the value of all samples is positive. @ggmarshall's implementation returns a np.nan waveform if there are negative sample. Is this what we want?

**Comment by jasondet** [comment]
I would prefer a different approach, which is to require that no processor should raise an exception for valid input data. It's better to keep problems from happening in the first place than to take a more lax approach and just try to catch them. Is the functionality of PR #129 worth jettisoning guaranteed validity?

**Comment by mmatteo** [comment]
@jasondet, I think it is normal that a processor might not be able to return a meaningful result for some classes of events. For instance, most of the current processor will have trouble with low energy events. The leading-edge trigger cannot find a trigger if there is no pulse and, in this case, any module depending on it -- e.g. the fixed time pickoff -- should not run.

**Comment by jasondet** [comment]
@mmatteo again, I would rather have fully populated output tables and check for strange values afterwards rather than have tables with values missing or rows skipped for some of the parameters. 

Or maybe I don't understand your recommendation. Considering your example -- if we are running a fixed time pickoff and expecting its output to be in the output table, what goes in the output table to hold the place for that row / event if we have decided to "turn off" FTP because of an error in one of its dependencies for that event's waveform?

**Comment by mmatteo** [comment]
@jasondet, why don't  we give a default value (e.g. nan) to the parameters declared in the output block? In this way, the parameters will have the default value if a processor does not run. I think we need to flag somehow values obtained by processors which "failed". 

The alternative would be that each processor gives a special value to the output parameters when its internal conditions are not met. This would force the duplication of code and requires a precise convention

**Comment by mmatteo** [comment]
I summarize here the outcome of the discussion at the analysis call. For the moment, a processor that is not able to return a meaningful output (e.g. when the trigger processor does not find a trigger) will turn NaN values. 

I would leave the issue open while we test whether this approach works. @iguinn @jasondet @wisecg, is this okay?

**Comment by jasondet** [comment]
Yes let's leave this here until it is tested. The goal is to ensure that a processor computes all NaN output for NaN on any input, and enforce it by a generic unit test that cycles through processors and their arguments sending NaN to each and checking that the output is NaN.

**Comment by sweigart** [comment]
What do we want to do for the "fixed_time_pickoff" processor?  I've found cases where the tp_0 is very late into the waveform due to pileup.  The index for the fixed-time pickoff can, in turn, be larger than the length of the waveform.  This condition is currently not checked for.  In such cases, do we just want to output NaN, or do we want to do something like min(tp_0+offset, last sample) for the pickoff?

@jasondet, @iguinn, @mmatteo, any preferences?

**Comment by mmatteo** [comment]
@sweigart, that's right. There are several processors that require a few changed. I have been waiting for @iguinn to implement a general function to handle this kind of exceptions. @iguinn, any update about this issue?

**Comment by jasondet** [comment]
As to @sweigart's specific question, I can imagine applications that would want either return value. For example, if you want "proper" E estimation, you don't want the pickoff time to float around, so NaN would be appropriate. On the other hand, if you just want an approximation of a pileup event energy, you want it to work for as late as the rising edge appears in the waveform, so you might want it to return the last valid sample. So probably we would want it to be a parameter of the processor?

**Comment by iguinn** [comment]
I've just submitted a pull request to at least partially address this. This adds the DSPFatal error that can be raised in a processor to abort processing. When this is thrown, it will also print some information about when it was thrown. This should be directly raised by the processor (i.e., no function for checking; this is due to a limitation of numba).

For errors where we do not want to abort, there are a couple options. The first one is what I suspect we are going with:
- Return NaN values, and check for them when writing to disk. This is simple and avoids the problems with the other options that I will describe. The biggest disadvantage, which Matteo and I discussed, is that this only works for floating point outputs. This means that for processors that return an array index, we now want to return a float to communicate "index not found". This is the current course we are going down.
- Raise a new type of exception called DSPWarning and handle it without aborting. This allows us to avoid the problem with ints in the NaN solution, but unfortunately if a single waveform throws a warning, it will halt the processor for all the other waveforms in the same block. This seems extremely non-ideal...
- Find a way to log warnings without raising an exception. This is difficult with numba because the processors do not have access to almost any outside information. There is an experimental feature that allows calling back into the python interpretter: https://numba.pydata.org/numba-doc/dev/user/withobjmode.html, but this seems risky to me
So those are a few options (if anyone has other ideas let me know). I think that just using NaN's is probably the best and simplest one, though.

**Comment by mmatteo** [comment]
Thank you very much @iguinn. @jasondet @wisecg are you okay with your proposal?

**Comment by wisecg** [comment]
Thanks Ian and Matteo.   I definitely agree that NaN/float handling is a lot simpler than the other two alternatives, since they would both require some unpleasant digging into Numba for not a lot of benefit.   

I'm ready to merge Ian's PR for this issue to the dev branch: https://github.com/legend-exp/pygama/pull/158

@jasondet any final comments before we merge?

**Comment by wisecg** [comment]
Okay, merged it.
