### ISSUE TITLE
ProcessingChain - index/time conversion of inputs parameters

### ISSUE THREAD

**Issue by mmatteo** [legend-exp/pygama#137]
I think we should be able to express the input parameters of a processor in the processingChain using time units. A config file should not depend on the sampling frequency. It would be great if also slicing operations could be performed using time values, e.g. not `waveform[0:800]` but `waveform[0:12.8*us]`

**Comment by iguinn** [comment]
Hi Matteo,
The decision was deliberate that processor inputs do not have units, and that units are handled by the ProcessingChain object instead. The reason for this is that the ufunc interface that numba uses (and that numpy processors use) doesn't easily accept units; we also wanted to keep the processors as simple as possible and avoid those kinds of conversions.

However, the ProcessingChain will parse units for you, including in slices, so the above thing you posted should work! The way it works is that a single clock unit is associated with the parsing chain, and is read out from the input waveform. Then, the scimath.units module is used to parse units and convert them into the clock unit. The converted numbers are fed to the processor.

One to-do item is to try to associate a unit with each waveform instead of with the ProcessingChain as a whole. This is something that will be necessary if we want to use downsampling, and will help a lot in working with FFTs of waveforms. I haven't yet put too much thought into how to do this, though.

**Comment by mmatteo** [comment]
Thanks a lot, @iguinn. This is very useful. We'll give it a try.

What does it happen if the conversion does not correspond exactly to one index? For instance, we try to slice `[0:20*ns]` but the wf is sampled at 16 ns?

**Comment by iguinn** [comment]
For int inputs, it rounds. Flooring is not preferred because some times floating point error can result in things like 16*ns being converted to 0.99999998 or something like that.

**Comment by mmatteo** [comment]
@iguinn, is it possible to dump a warning message when the time parameters is not a multiple of the sampling period? I think the user should know whether the parameters parsed through the JSON file are modified by the priocessing chain as a result of the cast from continuous to a discrete scale.

**Comment by iguinn** [comment]
Hey Matteo,
That's a good idea, I'll add something that checks if the results of a round are too far away from the result (like .00001 or something)
Ian

**Comment by mmatteo** [comment]
It sounds good. I leave the issue open. Please close it once this feature has been implemented
