### ISSUE TITLE
Processor List Conventions

### ISSUE THREAD

**Issue by ggmarshall** [legend-exp/pygama#138]
Hi, would it be good to start having some conventions for the processor list json files to make them easier to read and compare. I think most of them currently use 'wf_' for full waveform transforms and 'tp_' for time parameters. Is this worth formalising and extending to other objects so that you can quickly see what is being output by each processor?

**Comment by iguinn** [comment]
Yes, I agree. Obviously, we cannot force this, but we should write up a JSON format specification somewhere were we can include these recommendations (and so that people can lookup what everything means!)

We may also want to have some conventions for naming processors. We should adopt Jason's suggested convention for documenting them as well (I've been meaning to go through and do this for existing ones...).

I've also been questioning the decision to give each processor its own file. This was made to avoid having a single monolithic million line file, which I'd still like to avoid, but we might consider grouping related processors. For example, we could put the many trap_filter algorithms into a single trap_filters.py. The reason we originally didn't do this is because we were worried it would be hard to know what file to look in for a processor, but I think processors.py can act as an index to make that clear. @wisecg do you have any thoughts about this?

**Comment by mmatteo** [comment]
I like your idea. If we name all trap filter with trasp_somethingelse, it would be obvious to search for them into a trap.json file

**Comment by wisecg** [comment]
@iguinn @ggmarshall  I agree that `processors.py` is the best way to trace down what's being called from a JSON file.  Of course not everybody knows to look in that file and people often just end up browsing the list on GitHub.

I really like the idea of drafting a short formal specification for what we want to put into the JSON files.  We should just make a short Markdown (README.md) file and put it directly in the pygama/dsp directory.
