### ISSUE TITLE
`WaveformBrowser` and algebra in processors `args`

### ISSUE THREAD

**Issue by gipert** [legend-exp/pygama#195]
I don't understand how this is possible, since both `WaveformBrowser` and `raw_to_daq` use `build_processing_chain`, but if I have the following block in my DSP config:
```js
  "t0": {
    "function": "time_point_thresh",
    "module": "pygama.dsp.processors",
    "args": ["wf_pz", "2*bl_std", 0, 1, "t0"],
    "prereqs": ["wf_pz"],
    "unit": "16*ns"
},
```
`raw_to_daq` works without complaining, while `WaveformBrowser` throws:
```
>>> WaveformBrowser(f_raw, '/spms/raw', 'r2d_config.json', waveforms=['wf_blsub', 'wf_pz', 'wf_trap'], lines=['t0'])
[...]
ProcessingChainError: 2*bl_std is not a valid alphanumeric name
```
So my questions are:
1. Does pygama support basic algebra in processor arguments supplied via JSON?
2. If yes, what's causes this behaviour?

**Comment by iguinn** [comment]
Hey Luigi,
Yes, pygama supports this. This can be fixed by getting rid of the prereqs argument, since the prereqs can now be automated. I'd actually recommend against using prereqs anywhere.

The cause of this very puzzling and unhelpful error message is that bl_std is not included as a prereq, meaning that its processor is never run, and the variable is never added to the processing chain. As a result, when it tries parsing "2*bl_std" it fails and instead tries to add a variable by that name, which is not allowed. In the refactor branch I've tried clarifying these kinds of errors a bit.

**Comment by gipert** [comment]
Nasty! Indeed, I tried to debug it a bit by myself but the fix was definitely hard to realize. Thanks a lot Ian!
