### ISSUE TITLE
`ProcessingChain`: `LH5Store` can't write out 1d arrays with custom length from `get_multi_local_extrema`

### ISSUE THREAD

**Issue by patgo25** [legend-exp/pygama#317]
Hi all,

maybe it's just me being stupid  but if I try to write out an array (e.g. from the get_multi_local_extrema processor)

```
"vt_max_out, vt_min_out, n_max_out, n_min_out, flag_out" :{
            "function": "get_multi_local_extrema",
            "module": "pygama.dsp._processors.get_multi_local_extrema",
            "args": ["curr", "3*bl_std", "vt_max_out(10)", "vt_min_out(10)", "n_max_out", "n_min_out", "flag_out"],
            "unit":["ns","ns","none","none","none"]
```
I get the following error message:
````
LH5Store: do not know how to write vt_max_out of type ndarray
````

this also happens for example if you would try to save the current waveform:
````
"curr": {
            "function": "avg_current",
            "module": "pygama.dsp._processors.moving_windows",
            "args": ["wf_blsub", 1, "curr(len(wf_blsub)-1)"],
            "unit": "ADC"
        },
````
same message:
````
LH5Store: do not know how to write curr of type ndarray
````

But it doesn't happen if the dimension doesn't change e.g.  when writing out the waveform after baseline subtraction:
````
"wf_blsub":{
            "function": "subtract",
            "module": "numpy",
            "args": ["waveform", "bl_mean", "wf_blsub"],
            "unit": "ADC"
        },
````
This is saved with no problems (and I was already told that I shouldn't do that 😉  )

I didn't have the problem before switching to main.

Please help 🙃

**Comment by jasondet** [comment]
@iguinn can you take a look?

**Comment by gipert** [comment]
I can also reproduce this, I guess the regression was introduced with the refactor (#224). We need this for the SiPM DSP.

**Comment by patgo25** [comment]
[`elif isinstance(obj, Array):`](https://github.com/legend-exp/pygama/blob/main/src/pygama/lgdo/lh5_store.py#L640) doesn't returns false for
```
obj= array([[ 5., 11., 13., ..., 42., 46., 49.],
       [ 6., 18., 25., ..., 61., 65., 69.],
       [ 3.,  7., 11., ..., 35., 43., 47.],
       ...,
       [ 6., 11., 13., ..., 43., 63., 72.],
       [ 4.,  6., 14., ..., 39., 49., 51.],
       [ 1., 11., 18., ..., 36., 41., 59.]], dtype=float32)
```

is this correct?

**Comment by patgo25** [comment]
The changes to `ProcessingChain: LH5Store` in 32589d62013f8c06d8fc13e1f60fc58a4613247a 
fix the issue (at least temporarily)

Seems that somewhere those array get initialized as an `np.ndarray` not as an [ `pygama.lgdo.array `](src/pygama/lgdo/array.py) those it doesn't get recognized in [`elif isinstance(obj, Array):`](https://github.com/legend-exp/pygama/blob/main/src/pygama/lgdo/lh5_store.py#L640)

**Comment by iguinn** [comment]
The ProcessingChain will automatically try to figure out how to format the output variables based on what information is given to it. The code is in `src/pygama/dsp/processing_chain` lines 444-455:
- A LGDOWaveform will be used only if the frequency/offset are defined. This is why the current is not being read out, as ProcessingChain will not automatically assign frequency/offset when the size of the array changes since these cannot be easily deduced. In order to use this, in the json config file for args, you would do `curr(length, dtype, period=wf_in.period, offset=wf_in.offset + [offset caused by processor])`. If you do this, then `curr` will be output as an LGDOWaveform.
- A LGDOArray will be used for scalar outputs. The array part of it refers to the fact that there is one scalar value for each event
- What we need, then, is LGDOVectorOfVectors and LGDOArrayOfEqualSizeArrays. Neither of these are currently implemented and both are high on my to-do list. For the `get_multi_local_extrema processor` VectorOfVectors is what we want since there is a variable number of extrema for each event. For the case of `curr`, without assigning period/offset as above, a better behavior than using a numpy array would be to use LGDOArrayOfEqualSizeArrays

I will make implementing both the VectorOfVectors and ArrayOfEqualSizeArrays in a top priority

**Comment by patgo25** [comment]
Thanks, @iguinn that fixed it!
