### ISSUE TITLE
`Processing_chain` : `lh5Store` `load_nda` fails if waveform table

### ISSUE THREAD

**Issue by patgo25** [legend-exp/pygama#319]
Hi there,

again maybe its just me who is stupid, but:
`df = lh5.load_nda(file_raw, ['channel','waveform'],'spms/raw',idx_list=[*range(0,100)])`
results in error:
`AttributeError: 'WaveformTable' object has no attribute 'nda'`

But
`df = lh5.load_nda(file_raw, ['channel','waveform'],'spms/raw')`
~~works fine~~  also fails

for now I patchworked it with 97f2d80d09816f4ab77c7b355aee1604293b4c26

**Comment by patgo25** [comment]
Also works now, thanks!

**Comment by gipert** [comment]
The problem is that many LGDOs do not have a trivial representation as NumPy arrays (i.e. they don't have an `nda` attribute). Returning `values.nda` for a `WaveformTable` instance would work only in some cases (if `values` isn't a `VectorOfVectors`) and anyways ignores the `dt` and `t0` attributes.

The right way to fix this is to implement a `convert(library='numpy')` method in every LGDO class that returns a meaningful representation, then refactor `load_nda` to call this function on the read out object.

**Comment by jasondet** [comment]
does it work if you do this?

`df = lh5.load_nda(file_raw, ['channel','waveform/values'],'spms/raw')`

**Comment by patgo25** [comment]
Thank you, Jason. This works.
So it was me, in the end, being stupid.

**Comment by jasondet** [comment]
not at all! glad we figured out an easier solution
