### ISSUE TITLE
Data streams are not properly set when `DataLoader.set_cuts()` is not called

### ISSUE THREAD

**Issue by gipert** [legend-exp/pygama#516]
MWE:

```python
from pygama.flow import DataLoader
import numpy as np

dl = DataLoader(f"prodenv/prod-blind/ref/v01.06[setups/l200/dataloader]")

dl.set_files("period == 'p03' and run == 'r000' and datatype == 'phy' and timestamp == '20230312T043356Z'")
dl.set_datastreams([1027200], "ch")
#dl.set_cuts({"hit": "is_valid_0vbb == True"})
dl.set_output(columns=["energy_in_pe", "trapEmax_ctc_cal"], fmt="lgdo.Table")

el = dl.build_entry_list(tcm_level="tcm", save_output_columns=True)
data = dl.load(el)
print(len(np.unique(data["hit_table"].nda)))
```
Returns 181 (all the available streams) instead of 1. Uncommenting the `dl.set_cuts(...)` line produces the expected behavior.

**Comment by MoritzNeuberger** [comment]
I believe the problem is that `drop_idx`, which identifies the indices of the items to be dropped, including unselected streams, is not filled until after this if condition: 
https://github.com/legend-exp/pygama/blob/663d352ef9d2d5b73b0c5927dad88692a5f80442/src/pygama/flow/data_loader.py#L608
It checks if a cut is applied (for this level or at all), and if not, it skips the whole procedure. This could probably be solved by adding an additional condition to the if statement, checking if `self.table_list[level]` is set. I will try to implement it.
